package edu.hcmut.software_testing.project3.nxvhung.part_a.auto_test;// Generated by Selenium IDE

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import java.time.Duration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class EditStudentInfo {

  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() throws InterruptedException {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.get("https://www.rosariosis.org/demonstration/");
    driver.manage().window().setSize(new Dimension(1536, 816));
    driver.findElement(By.id("USERNAME")).sendKeys("administrator");
    driver.findElement(By.id("PASSWORD")).sendKeys("administrator");
    driver.findElement(By.cssSelector(".button-primary")).click();
    WebElement studentMenu = (new WebDriverWait(driver, Duration.ofSeconds(5)))
        .until(ExpectedConditions.elementToBeClickable(By.cssSelector(".menu-top > .Students")));
    studentMenu.click();

    WebElement findStudentButton = (new WebDriverWait(driver, Duration.ofSeconds(10)))
        .until(ExpectedConditions.elementToBeClickable(By.cssSelector(".button-primary")));
    findStudentButton.click();

    (new WebDriverWait(driver, Duration.ofSeconds(10)))
        .until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Group by Family")));

    driver.findElement(By.linkText("Hung NguyenXuan Vinh")).click();

    (new WebDriverWait(driver, Duration.ofSeconds(6)))
        .until(ExpectedConditions.visibilityOfElementLocated(By.id("divstudent_name")));

  }

  @After
  public void tearDown() {
//    driver.quit();
  }


  /**
   * Normal case, update Firstname run tC001001 to have edit data
   */
  @Test
  public void tC001001() {

    driver.findElements(By.cssSelector(".onclick")).get(0).click();

    WebElement studentsFirstName = driver.findElement(By.id("studentsFIRST_NAME"));
    studentsFirstName.click();
    studentsFirstName.clear();
    studentsFirstName.sendKeys("Rich");

    driver.findElement(By.cssSelector(".button-primary")).click();

    WebElement updated = (new WebDriverWait(driver, Duration.ofSeconds(10)))
        .until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".updated")));

    assertTrue(updated.isDisplayed());


  }

  /**
   * existing username run tC001001 to have edit data
   */
  @Test
  public void tC001002() {

    driver.findElements(By.cssSelector(".onclick")).get(1).click();
    WebElement username = driver.findElement(By.id("studentsUSERNAME"));
    username.clear();
    username.sendKeys("hungnxv");
    driver.findElement(By.cssSelector(".button-primary")).click();

    WebElement errorText = (new WebDriverWait(driver, Duration.ofSeconds(10)))
        .until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".error")));

    assertEquals(errorText.getText(), " Error: A user with that username already exists. Choose a different username and try again.");


  }

  /**
   * run tC001001 to update data
   */
  @Test
  public void tC001003() {

    driver.findElements(By.cssSelector(".onclick")).get(2).click();
    WebElement password = driver.findElement(By.id("studentsPASSWORD"));
    password.clear();
    password.sendKeys("123456");

    driver.findElement(By.cssSelector(".center > .button-primary")).click();
    js.executeScript("window.scrollTo(0,0)");
    WebElement score1 = (new WebDriverWait(driver, Duration.ofSeconds(10)))
        .until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".score1")));
    assertTrue(score1.isDisplayed());

  }

  /**
   * the password is weak at orange level, but admin still can save the student
   */
  @Test
  public void tC001004()  {

    driver.findElements(By.cssSelector(".onclick")).get(2).click();
    WebElement password = driver.findElement(By.id("studentsPASSWORD"));
    password.clear();
    password.sendKeys("H@ngnxv");

    driver.findElement(By.cssSelector(".center > .button-primary")).click();
    js.executeScript("window.scrollTo(0,0)");

    WebElement updated = (new WebDriverWait(driver, Duration.ofSeconds(10)))
        .until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".updated")));

    assertTrue(updated.isDisplayed());


  }

  /**
   * In vaid birthdate 1
   *
   */
  @Test
  public void tC001005()  {

    driver.findElements(By.cssSelector(".onclick")).get(6).click();
    driver.findElement(By.id("monthSelect1")).click();
    {
      WebElement dropdown = driver.findElement(By.id("monthSelect1"));
      dropdown.findElement(By.xpath("//option[. = 'February']")).click();
    }
    driver.findElement(By.id("daySelect1")).click();
    {
      WebElement dropdown = driver.findElement(By.id("daySelect1"));
      dropdown.findElement(By.xpath("//option[. = '31']")).click();
    }
    driver.findElement(By.id("yearSelect1")).click();
    {
      WebElement dropdown = driver.findElement(By.id("yearSelect1"));
      dropdown.findElement(By.xpath("//option[. = '2010']")).click();
    }

    driver.findElement(By.cssSelector(".center > .button-primary")).click();
    js.executeScript("window.scrollTo(0,0)");
    WebElement updated = (new WebDriverWait(driver, Duration.ofSeconds(10)))
        .until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".updated")));

    assertTrue(updated.isDisplayed());

  }

  /**
   * Future birthdate Choose the date in future, the system should show error message
   */
  @Test
  public void tC001006() {


    driver.findElements(By.cssSelector(".onclick")).get(6).click();
    driver.findElement(By.id("monthSelect1")).click();
    {
      WebElement dropdown = driver.findElement(By.id("monthSelect1"));
      dropdown.findElement(By.xpath("//option[. = 'February']")).click();
    }
    driver.findElement(By.id("daySelect1")).click();
    {
      WebElement dropdown = driver.findElement(By.id("daySelect1"));
      dropdown.findElement(By.xpath("//option[. = '31']")).click();
    }
    driver.findElement(By.id("yearSelect1")).click();
    {
      WebElement dropdown = driver.findElement(By.id("yearSelect1"));
      dropdown.findElement(By.xpath("//option[. = '2030']")).click();
    }

    driver.findElement(By.cssSelector(".center > .button-primary")).click();
    js.executeScript("window.scrollTo(0,0)");
    WebElement updated = (new WebDriverWait(driver, Duration.ofSeconds(10)))
        .until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".updated")));


    assertTrue(driver.findElements(By.cssSelector(".error")).size() != 0);
  }
}
